[package]
name = "lapce-lua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {version = "1.0"}
flate2 = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lapce-plugin = { git = "https://github.com/panekj/lapce-plugin-rust.git", branch = "volt" }
